### ISSUE TITLE
Portis is not working

### ISSUE THREAD

**Issue by miltonwg** [rsksmart/rns-manager-react#442]
When I try to log in to manager.rns.rifos.org on mainnet I get this modal and I cannot move forward.

**Steps to reproduce:**
1. go to manager.rns.rifos.org/
2. press connect wallet
3. follow portis indications
4. modal appears

![image](https://user-images.githubusercontent.com/5920311/129960584-2ce60419-a3a4-4475-af33-30e467fe3caa.png)

**Comment by jessgusclark** [comment]
Hey @miltonwg, 

Thanks, this has been reported with #428. I'm going to close this ticket and use the original one.
